### PR TITLE
updated dashboard

### PR DESCRIPTION
**Pull request by gauravchauhan2403**
dashboard is updated with logo. kindly go through the chosen design and verify it .Also suggest changes if needed

### CODE REVIEW

**Comment by codetheorem** [comment]
Can you share some screenshots?

**Comment by gauravchauhan2403** [comment]
Screenshot from 2020-08-19 14-59-12

**Comment by gauravchauhan2403** [comment]
is this design good or need to choose another.

**Review by codetheorem — CHANGES_REQUESTED** [review]
Dont delete yarn.lock file

**Review by codetheorem — CHANGES_REQUESTED** [review]
Change name in package.json file

**Pull request closed without merging**
